name: pbm_uas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.3.2
  google_sign_in: ^5.4.4
  firebase_storage: 

  dartz: ^0.10.1
  intl: 
  path:
  
  flutter_signin_button: ^2.0.0

  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300          
      - asset: assets/fonts/Poppins-Regular.ttf          
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf          
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf          
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 800
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 900        
  assets:
    - assets/images/
    - assets/svg/
